using BasicBlazorMovieApp.Components.Pages;
using BasicBlazorMovieApp.Models;
using static System.Net.Mime.MediaTypeNames;
using System.Data;
using System.Runtime.Intrinsics.X86;
using System;

namespace BasicBlazorMovieApp.Services;

public class MovieReviewService : IMovieReviewService
{
    private static readonly List<MovieModel> Movies =
        [
            new(1, "Highlander", "They are immortals, destined to live forever. They must duel down the ages until only one remains. Only decapitation by the sword can release them from their age-long battle for an incredible prize-power beyond imagination. From the Scottish Highlands of the Sixteenth century to present-day New York, they war for the Prize, while the fate of mortal man hangs in the balance.", "Images/Movies/Highlander.png", "Key to the film’s success is its casting. Fresh from Luc Besson’s cult hit Subway, Lambert brings an edgy presence to the lead role. His acting is not exactly refined but he’s intensely watchable, whether in action or sizing up his foes with a stare he later put down to being short sighted and robbed of his glasses on set. He’s ably matched by the inimitable Brown, who makes no attempt to pretend this is a serious film and throws himself into the villain’s part with exuberant relish. It’s a rare actor who can be that OTT and yet genuinely scary at the same time, but Brown, convincingly unhinged, pulls it off."),
            new(2, "Godfather", "Francis Ford Coppola's masterpiece features Oscar winner Marlon Brando as the patriarch of the Corleone family. Coppola paints a chilling portrait of a Sicilian family's rise and near fall from power in America, and the passage of rites from father to son. He masterfully balances the story between family life and the ugly business of crime in which they are engaged. Based on Mario Puzzo's best-selling novel, this graphic and brilliant film garnered ten Academy Award nominations.", "Images/Movies/Godfather.png", @"""Often films set at some distance lend a perspective to the here and now; they allow us to step back from our everyday skin to see who we really are. Bergman, for example, used a medieval knight in The Seventh Seal (1956) to reveal the crisis of faith in post-Christian Europe, and Robert Gardner, in Dead Birds (1963), used a primitive tribe of warriors in New Guinea to reveal the pathetic madness of a people, who like ourselves, have come to accept war as a normal way of life. And now The Godfather. How remote from actual experience, this world of violence and treachery, and yet how close to the soul of modern man.<br><br>

<p>The mafiosi, murderers and extortionists all, emerge from the film as believable people, when they might easily have become comic gangsters or monsters. Their world tips wildly from the orbit of normalcy; it is a closed world, where their ghastly brutal work is considered an ordinary way to support a family. In the idyllic Sicily sequence, the quaint customs, the fierce family loyalties and the rigid patriarchal formality have a rustic lovely charm; in the New York underworld they are pathetic anachronisms. Yet it is precisely these grotesque rural customs that humanize the members of the famiglia. They are human in the midst of a sordid world, and they do what they must to survive. That is their way, and perhaps the way of all of us.</p>

<p>Don Vito Corleone, meaning lionhearted, is an aging racketeer whose empire and health both show the stress of old age. Brando brings depth and sensitivity to the part, but because of his long established “star” quality he has taken too much of the prerelease publicity. Al Pacino, as his son Michael, gives a virtuoso performance which should bring him instant recognition. He is an idealistic college graduate, marked for a career in the foreign land outside the mob, but gradually the destructive world of his father overwhelms him in its evil. He matures both in humanity and ruthlessness to become a calculating killer and worthy heir to the Don's empire.</p>

<p>With The Godfather, Francis Ford Coppola, at 33 years of age, has become a major new talent among American directors. Two sequences in particular are set pieces of editing and directing, and are even more remarkable because of their different styles. During a baptism at which Michael is godfather, his men plan and execute a series of assassinations designed to consolidate his power over the other famiglie. The ceremony drags on endlessly, but the intercutting of the preparations for the murders builds a palpable tension. The explosion of violence at the end of the sequence snaps the tension; it is almost a relief to end it all despite the horror of the bloodletting.</p>

<p>The second sequence, by contrast, is a tender, loving family portrait of Don Corleone and his infant grandson playing together in the garden of his estate. The Don is weak, but with his grandchild he appears perfectly at peace with himself. At this moment, when he appears most fully human, he dies quietly and gently, alone with his grandchild and his flowers. Alone, each of the two scenes is a cameo of directorial art; together they show Coppola's immense versatility.</p>

<p>Nino Rota, who prepared the music for all of Federico Felliní's great films, blends Italian folk themes and America kitsch of the 1940's into an effective comment on the dramatic action.</p>

At three hours, The Godfather is by any reasonable standard too long to sustain interest, but most viewers will be sorry to see it end."""),
            new(3, "Last of the Mohicans", "From the creator of \"Miami Vice\" and the director of \"Manhunter\" comes this thrilling and highly acclaimed new adaptation of James Ferring Cooper's classic tale of adventure and romance starring Daniel Day-Lewis", "Images/Movies/LastOfTheMohicans.png", @"""""The Last of the Mohicans,"" a rapturous revision of the schoolroom classic, follows the trail blazed by ""Dances With Wolves"" and more recently ""Unforgiven."" A rousing frontier saga drawn from James Fenimore Cooper's ""The Leatherstocking Tales,"" it looks back with longing on the savage Eden of 18th-century America, a lush old-growth wilderness from which mountains rise like sleeping giants wreathed in cloud. Painstakingly, breathtakingly re-created by director Michael Mann, this landscape makes room for heroes with principles greater than the circumference of their biceps -- lean, smoldering, woodsy-smelling men.<br><br>

<p>Set in the 1750s during the French and Indian War, ""The Last of the Mohicans"" looks not only at the glorious possibilities of the New World, but at the violent collision of cultures that marked the beginning of European domination of the continent. The explosion brought about a sturdy hybrid represented by Hawkeye (Daniel Day-Lewis), the European-born adopted son of the patrician Mohican Chingachgook. That's not to say that Day-Lewis's portrait of Hawkeye isn't just a little bit Hollywood. A cross between Iron John and romance-novel cover boy Favio, the cerebral Brit promises to do for big hair what Don Johnson did for beard stubble in Mann's designer cop drama, TV's ""Miami Vice.""</p>

<p>Part modern romance, part historical re-creation, the story no longer has much to do with Cooper's original, which Mann slammed as plodding, racist and shallow -- especially when it came to its characterizations of Native Americans. Credited with the concept of the noble savage, Cooper would scarcely recognize Chingachgook, wonderfully played by American Indian Movement leader Russell Means. The story is based more on Randolph Scott's 1936 film of the same title, but Hawkeye has evolved from a celibate colonialist into a corset-popping proto-democrat.</p>

<p>Not that the movie pounds the drum for political correctness. Mann will have none of that buffalo bull. With the help of co-screenwriter Christopher Crowe, he's populated the film with cruel, jealous, lovesick, vengeful, worldly, proud, wealthy humans who happen to have sharp cheekbones and tobacco-colored skin. Neither as cuddly as the tribes of ""Dances With Wolves"" nor as bloodthirsty as those in ""Black Robe,"" they are nevertheless ruthless in combat.</p>

<p>Day-Lewis finds a dynamic match in Madeleine Stowe, who plays Cora Munro, the cultured daughter of the English officer in charge of Fort William Henry. Newly arrived in the Colonies, Cora and her younger sister Alice (Jodhi May) are rescued from a Huron war party by Hawkeye, his handsome brother Uncas (Eric Schweig) and Chingachgook, who hear their screams from a camp in the woods nearby. The three then accompany the women to Fort William Henry (rebuilt based on period documentation), which they find besieged by the French and their Huron allies. The small party slips through enemy lines into an ""Apocalypse Now"" of the period.</p>

<p>Despite the heroic efforts of the British and their Mohawk allies, the fort falls to the French when Col. Munro (Maurice Roeves) surrenders to Gen. Montcalm (Patrice Chereau). Montcalm's terms are generous: The British simply abandon the fort, return to their homes and fight no more. But Montcalm hadn't counted (or had he?) on the actions of his ally, Magua (Wes Studi), the Huron war captain who plots the massacre of the retreating troops, their women and children.</p>

<p>Many of the scenes, the massacre among them, are not for the squeamish; tomahawks and hunting knives leave especially gruesome wounds. Scalping is also graphically depicted, as is a particularly nasty form of heart surgery reminiscent of ""Indiana Jones and the Temple of Doom."" But this is after all a war movie -- it aims for smoke-snorting action with time out for some heavy smoldering. And happily Hawkeye is as good at smoldering as he is at loading a flintlock.</p>

<p>Indeed the movie sets new standards when it comes to pent-up passion between not only Cora and Hawkeye, but also between Alice and Uncas, who have their own bodices to burst. The four of them look into the camera with such a burning yearning, it's amazing the lens didn't melt all over the sets (which are authentically dressed down to the porcupine-quill knife sheaths). There's nothing explicit, but talk about his-and-hers heaving bosoms, the hearts within hammering to Trevor Jones and Randy Edelman's gorgeous epic score.</p>

<p>And if that isn't enough, there's the spectacular scenery: North Carolina's mysterious Smoky Mountains, which protect one of the nation's last two old-growth forests, stand in for the New York wilderness Cooper described. Of course, the movie's all the more poignant simply because that rugged paradise doesn't really exist anymore. In the real world, there are tacky souvenir shops and cheap motels down below. Mann's major achievement is that for two hours or so, he and his characters seem to have forgotten all that. They've thrown themselves into the project with urgency of a bucket squad at a barn fire.</p>

Mann, who's best known for such urban crime dramas as ""Vice"" and ""Manhunter,"" is equally at home whether the chase concerns a cigarette boat or a birch-bark canoe. He brings the same flair pairing action and style to ""The Last of the Mohicans,"" an attempt to resurrect and redefine the American hero. What were his values really? Mann theorizes that they were less European than Mohican, with an emphasis on the concept that no man has dominion over another. And apparently those Mohicans were some good kissers."""),
            new(4, "Rear Window", "Alfred Hitchcock amply demonstrates why he's been called 'The Master of Suspense' with this both witty and macabre tale of voyeurism and murder starring two of cinema's all-time favourites, Academy Award winners James Stewart and Grace Kelly.", "Images/Movies/RearWindow.png", @"""It is easy to review Rear Window for exhibitors. They should buy it and play it. They will make money with it and their audiences will be pleased by it, for, in addition to the Hitchcock mastery of suspense, it contains some very diverting comedy, an intriguing love story and a beautiful and practical female wardrobe created by Edith Head.<br><br>

<p>To review this film for Mr. Hitchcock’s fellow craftsmen in the motion picture industry is a little more than difficult. Years ago, he became master of telling the suspense story. But he’s never been one to recline on his laurels. In every script he sets himself new and difficult directorial problems and solves them with an ingenuity that never fails to put something fresh on the screen. In Rear Window, Jimmy Stewart has the role of a news photographer confined by a broken leg to a wheelchair. The situation anchors him in one small room and, almost throughout the film, the camera confines itself to his point of view. The invalid whiles away his boredom by spying on neighbors whose windows look out upon a common group of backyards. They include “Miss Torso,” a shapely show girl who practices in her underwear; a middle-aged salesman with an ailing, complaining wife; “Miss Lonely Heart,” an unhappy professional woman, and a number of prosaic but interesting characters.</p>

<p>As Stewart watches, a number of little things convince him that a murder has occurred in one of the apartments. At first he can convince neither his girlfriend (Grace Kelly), his nurse (Thelma Ritter) nor a detective friend (Wendell Corey). Finally, he gets the women on his side and gradually there builds up a tense, perilous and suspenseful struggle between the helpless photographer and the killer he has viewed only from a distance.</p>

<p>To progress his story and give it variety, Hitchcock has devised one of the most impressive sets in recent Hollywood history. And Hal Pereira and Joseph MacMillan Johnson have executed it magnificently. All the activities of a New York street are realistically viewed through a narrow alley. Varied life stories, pathetic, amusing and shocking are told by the glimpses through windows. Many of these are told in silent technique with only an occasional significant word or phrase drifting across the courtyard to the spectators. (The sound recording by Harry Lindgren and John Cope is a vital part of the picture’s style of story-telling.) Though most of the background action is told in longshots, Hitchcock has occasional need for two-shots and closeups. He gets these, very logically, by having his hero view his neighbors sometimes through binoculars and sometimes through the high-powered long distance lens of a still camera. Throughout the film, Hitchcock maintains a half-comic mood of spying and eavesdropping that makes the audience feel it is indulging in one of the most persistent of human foibles. The laughs are almost continuous.</p>

<p>Rear Window is one of the directional masterpieces of recent years. To keep it from being cold and technical, Hitchcock adds to it the warmest love story he’s ever placed on the screen. Here he capitalizes on the charm, beauty and acting powers of Grace Kelly. She appears as a wealthy and successful young woman, desperately in love with the adventurous and footloose photographer, who is afraid that marriage will tie him down. Intelligent, sophisticated, sweet and, at the same time, sexy, Miss Kelly plays the role with a yearning wistfulness that carries a bitter-sweet feeling of delightful longing to the audience. She makes you feel you are in love as you watch her. Even the sound of her kisses is haunting. Only the greatest stars have been able to achieve the sense of emotional spectator participation that radiates from this remarkable girl.</p>

In addition to revealing a new capacity for tenderness, the director shows an unsuspected flair for wise cracking comedy, particularly in the scenes where Miss Ritter and Corey make expert use of the bright dialogue in John Michael Hayes’ screenplay. Stewart is quite wonderful as the factor that holds all these elements together. Whether he is struggling to scratch an itching toe or writhing in the hands of a brutal killer, he at all times is an interesting and lovable human being a regular guy you are rooting for. It’s an entirely satisfying and entirely unusual movie."""),
            new(5, "Road House", "Meet Dalton. He's been shot, stabbed and kicked around all in the line of duty. He's 'cooler' a bouncer, a trained fighter hired to crowd control sophisticated nightclubs. Now he's needed by the owner of a rundown roadhouse to transform the seedy joint into a top nightspot.\r\n\r\nBut first he must battle a brutal crime boss whose greed and lust for power are legendary. Patrick Swayze is Dalton. And he does more than dance dirty in a spectacular action-thriller from the producer of Lethal Weapon and Die Hard.", "Images/Movies/RoadHouse.png", @"""In ""Road House,"" Patrick Swayze is Dalton, king of the coolers. A cooler, according to the film, is a kind of bar bouncer. He's the guy who's brought in when the situation gets too hot for the bouncer -- the bouncer's bouncer.<br><br>

<p>And with this, the educational portion of our broadcast comes to a close.</p>

<p>""Road House,"" the latest product from Joel Silver's Silver Pictures, the team that made ""Die Hard,"" ""Lethal Weapon,"" ""Predator"" and ""Action Jackson,"" is an ugly commingling of old Westerns, Zen chic and kung fu movies. Sleekly muscled, with cloaked eyes and loose-fitting Italian clothes, Dalton is an Armani marshal in a Wild West of neon and Miller Lite. A master of martial arts, he stands motionless through the long nights, his back against the bar, sipping coffee, black, waiting for some thug to put his cigarette out in somebody's face. ""My goodness,"" his expression reads, ""What appalling manners!!"" Setting down his mug, he'll wander over for a conversation with the gentleman, who, not being in a talkative mood, forces him to rearrange the brute's features.</p>

<p>See, Dalton doesn't like violence. He has a degree in philosophy. From NYU, no less. He must have done heavy reading in the Stoics, because early on we see him stitching up a knife wound in his shoulder. Later, when a foxy lady doctor, played by Kelly Lynch, asks if he would like an anesthetic for the nine staples she's about to put in his side to close another cut, he declines. ""Pain don't hurt,"" he says. Thank you, Socrates.</p>

<p>But wait, there's more juicy dialogue between these two. Impressed by the number of broken bones and stitches on his chart, not to mention his skill with a needle and thread, she tries to establish a rapport. ""Do you always win?"" she asks.</p>

<p>""Nobody wins a fight,"" he replies.</p>

<p>Convinced he's a peace-loving hombre, the doctor drops by his place of work, a bar called the Double Deuce, just in time to watch him bust up a few kneecaps. Before long, they're going out for coffee. Black.</p>

<p>Dalton has been hired by the owner of the Double Deuce to make the place suitable for decent folks to come and spend their money. The Double Deuce is the kind of place where they ""sweep up the eyeballs after closing."" Dalton changes all that, mostly by virtue of his manly example. Basically, Dalton tells his crew of young bouncers, he has only three rules: 1. Never underestimate your opponent; 2. Take it outside; 3. Be nice.</p>

<p>A fourth (unspoken) rule is: Never rip out an opponent's throat unless you're really, really mad.</p>

<p>Full of gratuitous mayhem, head-bashing, gay-bashing and woman-bashing, ""Road House"" has a malicious, almost putrid tone. Directed by the aptly named Rowdy Herrington, it updates the old Western formula of the honorable marshal who marches in to clean up a lawless Western town, amplifying the music (by the Jeff Healey Band) and the level of destruction in the process.</p>

<p>""Road House"" lays out its story with the subtlety of a wrestling match, and probably with less sharpness or savvy. Dalton's true adversary is a sinister local businessman named Wesley, who uses his gang of louts to squeeze a healthy cut of the take from the honest folks in town. Played by Ben Gazzara, Wesley is a happy sybarite who takes genuine, sadistic pleasure in his crimes. Though there is one funny moment when Wesley is seen cruising recklessly in his convertible, singing along to ""Sh-Boom Sh-Boom"" on the radio, the character is too crudely conceived to be either funny or engaging. He's a pig, and Gazzara can't make him anything more.</p>

The problem is, Dalton doesn't come across all that much better. When his old friend Wade (Sam Elliott) shows up, he refers to a man Dalton killed some years back in Memphis -- an incident that has left him emotionally scarred and, we assume, unable to settle down and find peace. And danged if history don't repeat itself. His relationship with Doc is also far from ennobling, especially with Lynch in the role. Though cast as a doctor, Lynch can't work up the brainpower to change expressions -- her features move in glacial time."""),
            new(6, "Star Trek IV", "The Voyage Home. The most acclaimed and, without a doubt, the most intriguing Star Trek adventure of all time. It's the 23rd century, and a mysterious alien power is threatening earth by evaporating the oceans and destroying the atmosphere. In their frantic attempt to save mankind, Kirk and his crew must time travel back to 1987 San Francisco where they find a world of punk, pizza and exact-change buses that are as alien as anything they've ever encountered in the far reaches of the galaxy.", "Images/Movies/StarTrek4.png", @"""Captain's log, Stardate 2290. Admiral James T. Kirk has more swash to buckle and Scotty is likewise broader around the beam. Middle age may have spread into space, but never have the Trekkers been more intrepid than in this rousing adventure. ""Star Trek IV: The Voyage Home"" is a flat-out four-thruster blast.<br><br>

<p>The episode is dedicated to the Challenger crew, but there's nothing solemn about this warp-time trip back to the 20th century. It crackles with comedy, but it's no space cartoon, nor self-lampoon. It's a happy, heartfelt chapter that reunites the original cast with the original TV format, shying away from the cold and epic scale of the preceding movie adventures. George Lucas may provide his incomparable Light and Magic for the splendid effects, but ""Star Wars"" is no longer a primary influence on the story.</p>

<p>Leonard Nimoy is the force behind this sparkling comic fiction; he not only reprises his role as the half-Vulcan Spock, but directs the screenplay which he cowrote with Steve Meerson, Peter Krikes and producer Harve Bennett. The story, an ecological allegory, makes full use of the vast Trekkie mythology provided by series creator Gene Roddenberry. The script, upbeat as it is uplifting, never wavers from Roddenberry's perennial notion that Earth's people will live long and prosper. But just barely.</p>

<p>In this instance, 23rd-century Earth is endangered by an alien mothership gone amuck as it searches the seas for the extinct humpback whale. The Trekkers must warp back to 20th-century San Francisco to save the whales -- and so mankind.</p>

<p>Exiled on Vulcan after destroying the Enterprise in ""III,"" the crew is forced to save the day in a stolen Klingon Bird of Prey (with cloaking device). Naturally, the di-lithium crystals destabilize, leaving the veteran mariners just 24 hours to beam up the leviathans and beat it back 'round the sun to the 23rd century. Cross-cutting between our present and their future, Nimoy manages to keep the proceedings as tense as they are funny.</p>

<p>Starfleet Command is on red alert. Meanwhile, the crewmen are in their little red suits, roaming the streets of '80s San Francisco, like Santa's helpers from a junta. Nobody notices even Spock, who has been recuperating from exaggerated reports of his death and left Vulcan wearing a long, white bathrobe. Space's answer to Bobby Ewing has lost none of his Vulcan faculties, but his human emotions are on the fritz. ""You really have gone where no man has gone before,"" says McCoy, who's even crankier now that he's matured.</p>

<p>DeForest Kelley returns as the blustering Bones, with James Doohan as Scotty, George Takei as Sulu, Walter Koenig as Chekov and Nichelle Nichols as Uhura. Eternally typecast, the actors and their characters have a 20-year history we share, like celestial soap opera. We know Uhura never wanted to get old from the TV shows, but now she contends with the inevitable gracefully. Albeit chunkily.</p>

<p>William Shatner, pleasingly paunchy and mellowed with the years, is no less the hero as Kirk, a man you can count on whether the nemesis is tribbles, Klingons or the whale god. Now, Shatner and Nimoy have hit upon a rejuvenating shtick -- as a sort of orbiting Odd Couple. Kirk patiently teaches the utterly logical Spock to cuss like they did in the '80s. It's something he learned from the literature of the period -- Jacqueline Susan, Harold Robbins, explains Kirk. ""Ah, the giants,"" Spock nods.</p>

Peopled with exotics and set against an ocean of stars, the plot is expected -- with elements of ""Back to the Future"" and ""Cocoon"" -- but never predictable. It reflects social change in the character of a liberated marine biologist (played with complete charm by Catherine Hicks), but it stubbornly returns to its old beloved self. Don't beam us up just yet, Scotty.""")
        ];
    public MovieModel? GetMovieById(int id)
    {
        return Movies.SingleOrDefault(m => m.Id == id);
    }

    public List<MovieModel>? GetMovies()
    {
        return Movies;
    }
}
